# Generated by Django 5.0 on 2024-01-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_accessinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accessinfo',
            name='nickname',
            field=models.CharField(max_length=50, verbose_name="bot's nickname"),
        ),
    ]
