# Generated by Django 5.0 on 2024-02-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_alter_question_answer_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'house', 'verbose_name_plural': 'houses'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='house name'),
        ),
        migrations.AlterField(
            model_name='house',
            name='house_number',
            field=models.PositiveIntegerField(verbose_name='house number'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.house', verbose_name='house'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.question', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(help_text='photo owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='helper_text',
            field=models.CharField(max_length=100, verbose_name='prompt helper text'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt',
            field=models.TextField(max_length=1000, verbose_name='prompt text'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_name',
            field=models.CharField(max_length=100, verbose_name='prompt name'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(max_length=500, verbose_name='answer text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(verbose_name='question number'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200, verbose_name='question text'),
        ),
        migrations.AlterField(
            model_name='video',
            name='question',
            field=models.ForeignKey(blank=True, help_text='related question', null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.question', verbose_name='question'),
        ),
        migrations.DeleteModel(
            name='AccessInfo',
        ),
    ]
