version: '2.4'

volumes:
  rmqdata:
    external: false
  pgdata:
    external: true
      

networks:
  botnet:
    external: false

services:
  admin:
    build: 
      context: ../..
      dockerfile: bot_site/Dockerfile
    expose:
      - 8000
    ports:
      - 8000:8000
    command:  bash bot_site/run.sh
    networks:
      - botnet
    depends_on:
      - postgres
      - rabbit

  bot:
    build:
      context: ../..
      dockerfile: bot/Dockerfile
    command: python bot/main.py
    networks:
      - botnet

  rabbit:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    ports:
     - 15672:15672
     
    restart: always
    environment:
     - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 536870912
    volumes:
      - rmqdata:/var/lib/rabbitmq
    networks:
      - botnet

  postgres: 
    image: postgres:16
    container_name: postgres_host
    hostname: postgres_host
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: full_house
    networks:
      - botnet
    volumes:
      - pgdata:/var/lib/postgresql/data
    shm_size: '256mb'