# Generated by Django 5.0 on 2023-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='house_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
