# Generated by Django 5.0 on 2023-12-30 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_house_house_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.house'),
        ),
    ]
