# Generated by Django 5.0 on 2024-01-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_house_house_number_alter_accessinfo_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='house',
        ),
    ]
