# Generated by Django 5.0 on 2024-01-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_house_address_alter_house_house_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_text',
            field=models.TextField(max_length=500, verbose_name='Answer text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.PositiveIntegerField(verbose_name='Question number'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=200, verbose_name='Question text'),
        ),
    ]
