# Generated by Django 5.0 on 2024-02-06 09:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_alter_house_options_alter_photo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredUsers',
            new_name='RegisteredUser',
        ),
        migrations.AlterModelOptions(
            name='registereduser',
            options={'verbose_name': 'registered user', 'verbose_name_plural': 'registered users'},
        ),
    ]
